apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kubelabx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yeonjin0814/frontend:v3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://localhost/api"
