apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: course-manager-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "list", "get"]
